export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_VOLCANOES = 'GET_VOLCANOES';
export const GET_VOLCANOES_FAIL = 'GET_VOLCANOES_FAIL';
export const GET_VOLCANO = 'GET_VOLCANO';
export const GET_VOLCANO_FAIL = 'GET_VOLCANO_FAIL';
export const ADD_VOLCANO = 'ADD_VOLCANO';
export const DELETE_VOLCANO = 'DELETE_VOLCANO';
export const UPDATE_VOLCANO = 'UPDATE_VOLCANO';
export const VOLCANOES_LOADING = 'VOLCANOES_LOADING';
export const VOLCANOES_LOADED = 'VOLCANOES_LOADED';
export const VOLCANO_LOADING = 'VOLCANO_LOADING';
export const VOLCANO_LOADED = 'VOLCANO_LOADED';


export const GET_WATERFALLS = 'GET_WATERFALLS';
export const GET_WATERFALLS_FAIL = 'GET_WATERFALLS_FAIL';
export const GET_WATERFALL = 'GET_WATERFALL';
export const GET_WATERFALL_FAIL = 'GET_WATERFALL_FAIL';
export const ADD_WATERFALL = 'ADD_WATERFALL';
export const DELETE_WATERFALL = 'DELETE_WATERFALL';
export const UPDATE_WATERFALL = 'UPDATE_WATERFALL';
export const WATERFALLS_LOADING = 'WATERFALLS_LOADING';
export const WATERFALLS_LOADED = 'WATERFALLS_LOADED';
export const WATERFALL_LOADING = 'WATERFALL_LOADING';
export const WATERFALL_LOADED = 'WATERFALL_LOADED';
